### ISSUE TITLE
little bug in vdr-getchannels

### ISSUE THREAD

**Issue by fiveten59** [bmihovski/ansible_vdr_scan#1]
Hi 
**I can't open an issue on your vdr-getchannels repository so i open it here hoping you could read.**

There is a little bug in output scripts:  there is a blank space before the name of the channel. In this case Vdr doesn't recognize correctly the logo of the channel.
Vdr want no blank space at the beginning of channels.conf row

Besides you can test mine app_params.py that you can find here: https://github.com/fiveten59/vdr-getchannels

**Comment by fiveten59** [comment]
Found the solution:
In getchhannesl.py file change  

tmpChCodes = tmpCh.split('title="Id:')
and substitute with
tmpChCodes = tmpCh.split(''' title="Id: ''')

I change the language part of the file too

Thankyou for the great job

**Comment by bmihovski** [comment]
Hi,
Thank you for your fix.
Should we ask the author for pull request, and how can we merge your and mine changes?
Cheers,
Boyan

**Comment by fiveten59** [comment]
I think that the best thing to do is open a new indipendent repo
After that i could suggest some change here and there (i really don't know
python)
(for example there is an important bug if you scan Hotbird or Astra or even
9.0 east - try to check it)

Last thing: merge app_getchannels.py too (it's more complete than yours)

Cheers
Gio

2018-01-06 22:28 GMT+01:00 bmihovski <notifications@github.com>:
